Add GetClassMembers endpoint
uclaacm/teach-la-go-backend pull request #46
Opened 2021-02-26 03:07 UTC by joshSi

2021-02-26 03:14 UTC, joshSi commented
Oh sorry meant to make a draft

2021-02-26 07:51 UTC, krashanoff commented
@joshSi you can reopen this pull request and then just edit it to mark it as a draft!

2021-03-11 19:09 UTC, krashanoff requested changes
Just a quick review. This looks good following a coding style change. Thanks for the work Josh!

2021-03-11 19:09 UTC, krashanoff commented on db/class.go
> +	)
You can probably get by removing the extra variable declarations here then use the short assignment statement, as you do later in the function.
```suggestion
	var req struct {
		CID string `json:"cid"`
		UID string `json:"uid"`
	}
```

2021-03-11 19:09 UTC, krashanoff commented on db/class.go
> +	res = make(map[string]User)
Related to the previous review comment:

```suggestion
	res := make(map[string]User)
```

2021-03-25 21:09 UTC, krashanoff approved these changes
We're seriously going to need to fix our tests. Aside from this, the changes look good. Thanks for your work Josh!

2021-03-27 20:54 UTC, merged

2021-03-27 21:08 UTC, joshSi commented
Closes #46

2021-03-27 21:11 UTC, joshSi commented
Closed #36