Add test coverage badge
uclaacm/teach-la-go-backend pull request #54
Opened 2021-05-07 06:27 UTC by reginawang99

2021-05-07 18:44 UTC, reginawang99 commented on .github/workflows/go-coverage.yml
> +      run: |
change to singular line

2021-05-07 19:02 UTC, reginawang99 commented on .github/workflows/go-coverage.yml
> +        go test -v ./... -covermode=count -coverprofile=coverage.out
maybe compile this with the other go tests rather than it being its own file?

2021-05-07 21:37 UTC, lumisphere902 requested changes
Hi Regina, thanks for working on this. All of it looks pretty good; I just have one concern. It seems like there’s a failing check because of the coverage? I’d prefer if that wasn’t there, but otherwise LGTM

2021-05-08 21:00 UTC, reginawang99 commented
# Coveralls Coverage
Coveralls will fail if coverage drops by more than 10%
You can modify this in Coveralls like so
![image](https://user-images.githubusercontent.com/29292203/117520582-be08d000-af5d-11eb-8bbd-3a7761435bb2.png)

# Once tests are fixed
- remove the `test` job
- remove `continue-on-error: true` from `test-coverage`

2021-05-09 03:20 UTC, krashanoff approved these changes
Thanks for the changes Regina. LGTM.

2021-05-09 03:23 UTC, merged