Refactor GetClass to handler conventions.
uclaacm/teach-la-go-backend pull request #59
Opened 2021-06-12 21:18 UTC by krashanoff

Another refactor PR of a GET-style endpoint. This one modifies our `GetClass` endpoint to use handler-style conventions, and adds a few tests. I'll try and make the tests more comprehensive, but this was something I just wanted to get in a draft PR at least.

I also removed our defunct class tests since I was replacing them with mocked ones.

2021-06-13 23:21 UTC, lumisphere902 requested changes
Refactor LGTM. I think while we're changing these we might as well update the tests too.

2021-06-13 23:21 UTC, lumisphere902 commented on handler/class_test.go
> +			assert.Equal(t, http.StatusOK, rec.Code)
I might be missing something but it doesn't seem like we're verifying that the programs are actually being returned here.

2021-06-13 23:21 UTC, lumisphere902 commented on handler/class_test.go
> +			require.NotEmpty(t, rec.Body)
Same here

2021-07-11 20:47 UTC, krashanoff commented
100% test coverage has been achieved, the PR is ~1m old, and the functionality is there. I am going to take an executive action and say this is good to merge after a little integration testing from my end.

2021-07-15 00:52 UTC, merged