Refactor delete program
uclaacm/teach-la-go-backend pull request #98
Opened 2022-05-25 01:56 UTC by ArshMalik02

Implemented delete program handler.

Comment out tests and fix them in handler/program_test.go

2022-05-25 21:05 UTC, lumisphere902 requested changes
Hey Arsh, what you have here looks great! Just a couple of changes left, and one more thing: you should delete the `db/program.go` implementation, then change the handler in `server.go` to use your new version. After that, make sure to test locally, and you should be good to merge!

2022-05-25 21:05 UTC, lumisphere902 commented on handler/program.go
> +	c.StoreUser(c.Request().Context(), u)
```suggestion
	err = c.StoreUser(c.Request().Context(), u)
	if err != nil {
		return err
        }
```
Something quick like this should make the linter happy

2022-05-25 21:05 UTC, lumisphere902 commented on handler/program.go
> +		c.StoreClass(c.Request().Context(), cls)
Same here

2022-05-25 21:05 UTC, lumisphere902 commented on handler/program.go
> +	// pref := d.Collection(programsPath).Doc(toDelete)
Remove comment

2022-05-25 23:06 UTC, ArshMalik02 commented
Incorporated the suggestions

2022-05-28 01:49 UTC, lumisphere902 approved these changes
LGTM. Thanks for all your hard work! This goes a long way into increasing the robustness of the tests and overall code quality. Feel free to merge whenever. :)

2022-05-28 02:21 UTC, merged